Repository Google-Developer-Student-Clubs-TUK/GDGoc-TUK-Official-Frontend, pull requests merged in 2025-06, with the labels that each got.

#18 [Design/17] Footer 리퍼블리싱
  package-lock.json
  public/icon/logo.png
  src/app/_components/_layout/Footer.tsx
  yarn.lock
Labels: 🎨 Design

#16 [Feat/7] Recruitment page 퍼블리싱
  package-lock.json
  package.json
  public/icon/slideup_arrow.svg
  public/image/recruitment-bg.png
  src/app/(route)/memberManage/_component/volunteer/VolunteerModal.tsx
  src/app/(route)/recruitment/components/AvailableApply.tsx
  src/app/(route)/recruitment/components/SetPeriod.tsx
  src/app/(route)/recruitment/components/SetPeriodModal.tsx
  src/app/(route)/recruitment/components/UnAvailableApply.tsx
  src/app/(route)/recruitment/page.tsx
  src/app/globals.css
  tailwind.config.ts
  yarn.lock
Labels: ✨ feat

#26 [Design/25] 메인페이지 스타일링 수정
  package-lock.json
  public/icon/main/bubbleTail.png
  public/icon/main/gdgoc.png
  public/icon/main/vector1.png
  public/image/main-bg.png
  public/image/main-bg.svg
  src/app/(route)/main/_component/Activity.tsx
  src/app/(route)/main/_component/ActivityItem.tsx
  src/app/(route)/main/_component/CountItem.tsx
  src/app/(route)/main/_component/IntroduceTitle.tsx
  src/app/(route)/main/_component/ParticipatedCount.tsx
  src/app/(route)/main/_component/SlideIn.tsx
  src/app/(route)/main/_component/SpeechBubble.tsx
  src/app/(route)/main/_component/Title.tsx
  src/app/(route)/main/page.tsx
  src/app/_hook/useScrollSection.ts
  src/app/_utils/scrollUtils.ts
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
  yarn.lock
Labels: 🎨 Design, 🪄 Enhancement

#27 feat: 헤더 리퍼블리싱 및 드롭다운
  src/app/_components/_layout/Header.tsx
  yarn.lock
Labels: 🎨 Design, 🪄 Enhancement, ✨ feat

#33 [Feat/32] 관리자 확인 페이지
  src/app/(route)/login/page.tsx
  src/app/(route)/main/_component/Title.tsx
  src/app/(route)/recruitment/page.tsx
  src/app/_components/_layout/Header.tsx
  src/app/_hook/useLeaderCheck.ts
  src/app/_providers/action.ts
Labels: ✨ feat

#39 [Design/38] 로그인 페이지 리퍼블리싱
  src/app/(route)/login/page.tsx
  src/app/_components/_ui/Button.tsx
Labels: 🎨 Design
